
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.servicePort }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.servicePort }}
            initialDelaySeconds: 5
            periodSeconds: 5
