"""Export API contracts (`API.md §6.8`)."""

from __future__ import annotations

import uuid
from typing import Any

from pydantic import Field, field_validator

from app.core.constants import DEFAULT_EXPORT_TYPES, TargetLanguage
from app.models.enums import ExportType
from app.schemas.common import ResponseModel, StrictModel


class ExportRequest(StrictModel):
    """Request to trigger exports for a project."""

    export_types: list[ExportType] = Field(
        default_factory=lambda: [ExportType(t) for t in DEFAULT_EXPORT_TYPES],
        min_length=1,
        description="Artifacts to produce. `github` pushes to a repository and is opt-in.",
    )
    # Bounded and character-restricted: these flow into GitHub API URLs, git refs and a
    # Dockerfile, and unbounded strings used to reach them verbatim.
    github_repo_name: str | None = Field(
        default=None,
        max_length=100,
        pattern=r"^[A-Za-z0-9._-]+$",
        description="Repository name for GitHub export, e.g. stripe-integration",
    )
    github_org: str | None = Field(
        default=None,
        max_length=39,
        pattern=r"^[A-Za-z0-9-]+$",
        description="GitHub organization for repo creation",
    )
    github_private: bool = Field(default=True, description="Whether the repo should be private")
    github_branch: str = Field(
        default="main", max_length=255, pattern=r"^[A-Za-z0-9._/-]+$", description="Branch to push to"
    )
    github_commit_message: str = Field(
        default="Generated by APIWeaver", min_length=1, max_length=1000, description="Commit message"
    )
    docker_image_name: str | None = Field(
        default=None,
        max_length=255,
        pattern=r"^[a-z0-9][a-z0-9._/:-]*$",
        description="Docker image name for Docker export",
    )
    target_languages: list[TargetLanguage] | None = Field(
        default=None, min_length=1, max_length=2, description="Target languages, e.g. ['python', 'node']"
    )

    @field_validator("github_branch")
    @classmethod
    def _valid_ref(cls, value: str) -> str:
        # git check-ref-format rules the pattern cannot express (no lookarounds).
        if ".." in value or value.startswith(("/", "-")) or value.endswith(("/", ".lock", ".")):
            raise ValueError("not a valid branch name")
        return value

    @field_validator("export_types")
    @classmethod
    def _dedupe(cls, value: list[ExportType]) -> list[ExportType]:
        return list(dict.fromkeys(value))


class ExportResponse(ResponseModel):
    """Response from triggering exports."""

    export_id: uuid.UUID
    artifacts: list[dict[str, Any]]


class MCPExportResponse(ResponseModel):
    """Response for MCP export."""

    mcp_manifest_url: str
    tools_generated: int
    flagged_destructive: int


class ExportArtifactResponse(ResponseModel):
    """Metadata for a single export artifact."""

    id: uuid.UUID
    export_id: uuid.UUID
    export_type: str
    artifact_name: str
    s3_key: str
    metadata: dict[str, Any] | None = None
    created_at: str | None = None