"""GitHub-related schemas (Phase 4)."""

from __future__ import annotations

from pydantic import BaseModel


class GitHubAuthUrlResponse(BaseModel):
    auth_url: str
    state: str


class GitHubCallbackRequest(BaseModel):
    code: str
    state: str


class GitHubInstallation(BaseModel):
    id: int
    account: str
    account_type: str


class GitHubStatusResponse(BaseModel):
    connected: bool
    github_username: str | None = None
    installations: list[GitHubInstallation] = []


class GitHubConnectionResponse(BaseModel):
    id: str
    github_username: str
    connected_at: str
    scopes: list[str]


class GitHubRepo(BaseModel):
    id: int
    name: str
    full_name: str
    private: bool
    owner: str
    default_branch: str = "main"


class GitHubReposResponse(BaseModel):
    repos: list[GitHubRepo]


class GitHubExportRequest(BaseModel):
    repo_name: str
    org: str | None = None
    private: bool = True
    branch: str = "main"
    commit_message: str = "Generated by APIWeaver"
